apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --chart
    kompose.service.expose: api.barriquesoft.local
    kompose.service.type: nodeport
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: barrique-server
  name: barrique-server
spec:
  replicas: 2
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --chart
        kompose.service.expose: api.barriquesoft.local
        kompose.service.type: nodeport
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: barrique-server
    spec:
      containers:
      - args:
        - rails
        - server
        - -b
        - 0.0.0.0
        - -p
        - "3010"
        command:
        - /opt/tgw/app/lib/docker-entrypoint.sh
        env:
        - name: RAILS_ENV
          value: development
        image: tgwconsulting/barrique-api:latest
        name: barrique-server
        ports:
        - containerPort: 3010
        resources: {}
      restartPolicy: Always
status: {}
