apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --chart
    kompose.service.expose: api.barriquesoft.local
    kompose.service.type: nodeport
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: barrique-server
  name: barrique-server
spec:
  ports:
  - name: "3010"
    port: 3010
    targetPort: 3010
  selector:
    io.kompose.service: barrique-server
  type: NodePort
status:
  loadBalancer: {}
